### ISSUE TITLE
Amatria 5th Birthday Party Image Galleries Link

### ISSUE THREAD

**Issue by ezengels** [cns-iu/cns-website-issues#3]
Add the below link as a hyperlink to the end of "Amatria 5th Birthday Celebration (9:00am–10:00am), Indiana University, Bloomington, IN" on the Amatria page: https://cns.iu.edu/amatria.html. It should be formatted as:

Amatria 5th Birthday Celebration (9:00am–10:00am), Indiana University, Bloomington, IN (Photos)

[https://photos.app.goo.gl/n7zrro1Pj8gZYfWt6]

**Comment by ezengels** [comment]
@bhushankhope I don't see this up yet, could you take a look?

**Comment by bhushankhope** [comment]
@ezengels fixed it, its live now
