### ISSUE TITLE
Amatria Page Errors

### ISSUE THREAD

**Issue by ezengels** [cns-iu/cns-website-issues#4]
I noticed a couple of errors on the Amatria page in the event section that need to be corrected.

1. The event "Amatria tour for participants of [ISSI Conference](https://cns-iu.github.io/workshops/2023-07-02_issi/), Indiana University, Bloomington, IN" should be in 2023, not 2024. 

2. The event "Amatria tour for Research Experiences for Undegraduates (3:45pm–4:15pm), Indiana University, Bloomington, IN ([Photos](https://photos.app.goo.gl/vkPSyjiZVr7zJQjb9))" of June 21, 2022 has the word "Undergraduates" misspelled.

**Comment by bhushankhope** [comment]
Fixed the typo. Please review here
https://cns.iu.edu/amatria.html
