### ISSUE TITLE
Profile updates for Danial Qaurooni

### ISSUE THREAD

**Issue by LibbyUX** [cns-iu/cns-website-issues#5]
## 2 profile updates for Danial Qaurooni:
- [x] Danial's name is misspelled. Please adjust Daniel to Danial in his profile.
- [x] Add Danial's website to the background section of his profile.

Danial Qaurooni needs his website, https://dequeue.cc/, added to his profile at https://cns.iu.edu/current_team/bio/dan-qaurooni.html

Please add this website to the bottom of Dan's background section. It will read/look like this:

```
I come from a Computer Science background but I have become increasingly interested in design research and anthropology of technology. My dissertation was an ethnographic study of the Food Computer (2015-2020), a design project at the MIT Media Lab. At CNS, my main focus will be design research re HuBMAP and the associated projects. Using a mixture of qualitative and quantitative methods, my goal is to bridge the technical with the social and generate practical insights that can inform the design process.

Danial Qaurooni's website: https://dequeue.cc/ 
```

![image](https://github.com/cns-iu/cns-website-issues/assets/97060856/09b5b625-4c37-4db5-9192-3fbdc990f921)

**Comment by bhushankhope** [comment]
@LibbyUX updated.

**Comment by LibbyUX** [comment]
Thank you @bhushankhope!

One last small request: Can we add a space for the website line and embed the URL?

See Andi's profile for desired outcome:
<img width="514" alt="Screenshot 2024-06-20 at 11 18 07 AM" src="https://github.com/cns-iu/cns-website-issues/assets/97060856/e3078ef6-db4c-428f-b4b0-4d4f78f9330e">

**Comment by bhushankhope** [comment]
@LibbyUX fixed. closing this issue
