### ISSUE TITLE
Adding the New Member of CNS to the Website

### ISSUE THREAD

**Issue by zeynepamac01** [cns-iu/cns-website-issues#9]
### Education
12th Grade, Bloomington High School North
### Background
I am a graphic designer and social media supporter at CNS. I am into digital art and drawing,
and I have been interested in graphic design for years. I have gained experience from several
projects as a high school student. I always thought I would pursue a major related to graphic
design, but then I discovered Intelligent Systems Engineering, which is now my future major.
This discovery changed my career pathway, leading me to focus more on STEM.
### Personal
I like to spend my time traveling, journaling, and drawing. I often use my iPad to create art at
school and during my free time. This allows me to express my creativity and continuously
improve my artistic skills. Hiking is also an activity that I enjoy with my family.
![zeynep profile photo](https://github.com/user-attachments/assets/2e3f28b4-2c1a-448c-9754-ecdb2372ef3b)

**Comment by bhushankhope** [comment]
@zeynepamac01 what is your role and start date?

**Comment by zeynepamac01** [comment]
> @zeynepamac01 what is your role and start date?

My role is "Graphic Designer and Social Media supporter" and my start date is July 10, 2024.
